name: Deploy Hugo to GitHub Pages

on:
  push:
    branches: [ source ]  # 仅监控source分支的推送

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 监测 source 分支
        uses: actions/checkout@v4
        with:
          ref: source  # 明确检出source分支

      - name: hugo 设置，生成静态文件
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.125.7'  # 指定Hugo版本
          extended: true  # 启用扩展版
      - name: 删除符号链接
        run: rm -f /home/runner/work/hugo/hugo/static/_resources
      - name: 复制图片
        run: cp -r //home/runner/work/hugo/hugo/static/00-assets/ /home/runner/work/hugo/hugo/static/_resources
      - name: Build static files
        run: hugo --minify --gc

      - name: Set up SSH  
        uses: webfactory/ssh-agent@v0.8.0  
        with:  
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          
      - name: 发布到 main 分支  
        uses: peaceiris/actions-gh-pages@v3  
        with:  
          github_token: ${{ secrets.GITHUB_TOKEN }}  
          publish_dir: ./public  
          publish_branch: main  # 正确参数名称
          force_orphan: true  # 强制清空目标分支历史

