name: Deploy Hugo to GitHub Pages

on:
  push:
    branches: [ source ]  # 仅监控source分支的推送

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 监测 source 分支
        uses: actions/checkout@v4
        with:
          ref: source  # 明确检出source分支

      - name: hugo 设置
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.125.7'  # 指定Hugo版本
          extended: true  # 启用扩展版

      - name: 删除符号链接
        run: rm -f /home/runner/work/hugo/hugo/static/_resources

      - name: 复制图片
        run: cp -r //home/runner/work/hugo/hugo/static/00-assets/ /home/runner/work/hugo/hugo/static/_resources

      - name: hugo 生成静态文件
        run: hugo --minify --gc

      - name: 发布到 main 分支  
        uses: peaceiris/actions-gh-pages@v4
        with:
          deploy_key: ${{ secrets.SSH_PRIVATE_KEY }}
          publish_dir: ./public  
          publish_branch: main  # 正确参数名称
          force_orphan: true  # 强制覆盖目标分支
          external_repository: git@github.com:zero3737/hugo.git
          github_token: ""
        env:  
          # 配置 Git 用户信息  
          GIT_USER_NAME: "root"  
          GIT_USER_EMAIL: "root@localhost"
          

